name: Deploy preview

on:
  push:
    branches:
      - 'post/**'

jobs:
#   preBuild:
#     runs-on: ubuntu-latest
    
#     outputs:
#       preview: ${{ steps.setPreview.outputs.preview }}

#     steps:

#     - name: Git fetch
#       run: |
#         git init
#         git remote add origin https://github.com/mseninc/blog.git
#         git fetch --depth 1

#     - name: Prepare env PREVIEW
#       id: setPreview
#       run: |
#         BRANCH_NAME=${GITHUB_REF#refs/heads/}
#         PREVIEW=`git -c core.quotepath=false diff origin/release origin/${BRANCH_NAME} --name-only | grep .md | head -n 1 | sed -E "s/.*\/([^/]+)\/[^./]+\.md$/\1/"`
#         echo ::set-output name=preview::${PREVIEW}

  build:
#     needs: preBuild
#     if: ${{ needs.preBuild.outputs.preview != '' }}
    
    runs-on: ubuntu-latest
    
    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTENT_PATH: ${{ github.workspace }}/content
      GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
    
    steps:
    
#     - name: Prepare env PREVIEW
#       run: echo "PREVIEW=${{ needs.preBuild.outputs.preview }}" >> $GITHUB_ENV

    - name: Prepare env BRANCH_KEY
      run: echo "BRANCH_KEY=${GITHUB_REF#refs/heads/post/}" >> $GITHUB_ENV

#     - name: Prepare env PATH_PREFIX
#       run: echo "PATH_PREFIX=/${BRANCH_KEY}" >> $GITHUB_ENV

    - name: Checkout generator
      uses: actions/checkout@v2
      with:
        repository: mseninc/blog-gatsby

#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         path: content

    - name: Checkout contents
    - run: mkdir -p content
    
    - name: Checkout contents
      working-directory: content
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        git init
        git remote add origin https://github.com/mseninc/blog.git
        git fetch --depth 1
        git config core.sparsecheckout true
        echo author.yaml >> .git/info/sparse-checkout
        git -c core.quotepath=false diff origin/release origin/${BRANCH_NAME} --name-only >> .git/info/sparse-checkout
        cat .git/info/sparse-checkout
        git checkout origin/${BRANCH_NAME}
        PREVIEW=`git -c core.quotepath=false diff origin/release origin/${BRANCH_NAME} --name-only | grep .md | head -n 1 | sed -E "s/.*\/([^/]+)\/[^./]+\.md$/\1/"`
        echo "PREVIEW=${PREVIEW}" >> $GITHUB_ENV

    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v2
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-blog-preview-${BRANCH_KEY}
        restore-keys: |
          ${{ runner.os }}-blog-preview-${BRANCH_KEY}
    
    - run: ls -la

    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: node_modules/.bin/gatsby build --verbose

    - name: Deploy post files
      run: "aws s3 sync public s3://msen-blog-preview --exclude '*' --include '*.html' --include '*/app-data.json' --include '*/page-data.json'"

    - name: Deploy other files
      run: "aws s3 sync public s3://msen-blog-preview --size-only --exclude '*.html' --exclude '*/app-data.json' --exclude '*/page-data.json'"
