name: Deploy release

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTENT_PATH: ${{ github.workspace }}/content
      GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: mseninc/blog-gatsby

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: content
        
    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v2
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-gatsby-build
        restore-keys: |
          ${{ runner.os }}-gatsby-build
    
    - run: ls -la

    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: node_modules/.bin/gatsby build --verbose

    - name: Deploy post files
      run: aws s3 sync public s3://msen-blog-release --exclude '*' --include '*.html' --include '*/app-data.json' --include '*/page-data.json' --delete

    - name: Deploy other files
      run: aws s3 sync public s3://msen-blog-release --size-only --exclude '*.html' --exclude '*/app-data.json' --exclude '*/page-data.json' --delete
