name: Deploy preview

on:
  push:
    branches:
      - 'post/**'

jobs:
  preBuild:
    runs-on: ubuntu-latest

    steps:
    
    - name: ''
      run: |
        git --version
        PREVIEW=`git -c core.quotepath=false diff release HEAD --name-only | grep .md | head -n 1 | sed -E "s/.*\/([^/]+)\/[^./]+\.md$/\1/"`
        echo "PREVIEW=${PREVIEW}" >> $GITHUB_ENV
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "PATH_PREFIX=/${BRANCH_NAME}" >> $GITHUB_ENV
        echo "url=https://preview.msen.blog/${BRANCH_NAME}/${PREVIEW}" >> $GITHUB_ENV
        cat $GITHUB_ENV
        
  build:
    needs: preBuild
    if: "${{ env.PREVIEW != '' }}"
    
    runs-on: ubuntu-latest
    
    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTENT_PATH: ${{ github.workspace }}/content
      GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: mseninc/blog-gatsby

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: content
        
    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v2
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-gatsby-build
        restore-keys: |
          ${{ runner.os }}-gatsby-build
    
    - run: ls -la

    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: node_modules/.bin/gatsby build --verbose --prefix-paths

    - name: Deploy post files
      run: "aws s3 sync public s3://msen-blog-preview/${BRANCH_NAME} --exclude '*' --include '*.html' --include '*/app-data.json' --include '*/page-data.json' --delete"

    - name: Deploy other files
      run: "aws s3 sync public s3://msen-blog-preview/${BRANCH_NAME} --size-only --exclude '*.html' --exclude '*/app-data.json' --exclude '*/page-data.json' --delete"
