name: Deploy release

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONTENT_PATH: ${GITHUB_WORKSPACE}/content
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: mseninc/blog-gatsby

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: content

    - run: ls -la

    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: node_modules/.bin/gatsby build --verbose

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp --recursive --region ap-northeast-1 build s3://msen-blog-release
