name: Make indecies

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Create .id files
      run: |
        ./scripts/make-index.sh
    - name: Git commit
      run: |
        git add -N .
        if ! git diff --exit-code --quiet
        then
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Add indecies" -a
          git push origin main
        fi
