name: Comment preview URLs to Pull request

on:
  pull_request:
    branches:
      - release
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && contains(github.head_ref, 'post/')

    environment:
      name: Preview
    
    env:
      BASE_URL: https://preview.msen.blog/
      HEAD_REF: ${{ github.head_ref }}

    steps:

    - name: List preview urls
      id: list-url
      run: |
        git init
        git remote add origin https://github.com/mseninc/blog.git
        git fetch --depth 1
        chmod +x .github/scripts/list-preview-url.sh
        echo "URL_LIST<<EOF" >> $GITHUB_ENV
        .github/scripts/list-preview-url.sh $BASE_URL $HEAD_REF | tee -a $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Comment to PR
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'Preview URL:\n${{ env.URL_LIST }}' });

