name: Comment URL to Pull request

on:
  pull_request:
    branches:
      - release
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && contains(github.head_ref, 'post/')

    environment:
      name: Preview
    
    env:
      BASE_URL: https://preview.msen.blog/

    steps:

    - name: Make preview url
      run: echo "PREVIEW_URL=${BASE_URL}${GITHUB_REF#refs/heads/post/}" >> $GITHUB_ENV

    - name: Comment PR
      uses: actions/github-script@0.3.0
      if: 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: '${{ env.PREVIEW_URL }}' });
