name: Comment preview URLs to Pull request

on:
  pull_request:
    branches:
      - release
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && contains(github.head_ref, 'post/')

    environment:
      name: Preview
    
    env:
      BASE_URL: https://preview.msen.blog/
      HEAD_REF: ${{ github.head_ref }}

    steps:

    - name: List preview urls
      id: list-url
      run: |
        git init
        git remote add origin https://github.com/mseninc/blog.git
        git fetch --depth 1
        git config core.sparsecheckout true
        echo .github/ >> .git/info/sparse-checkout
        git checkout $HEAD_REF
        chmod +x .github/scripts/list-preview-url.sh
        .github/scripts/list-preview-url.sh $BASE_URL $HEAD_REF | tr '\n' ',' > url_list
        URL_LIST=`cat url_list`
        cat URL_LIST
        echo URL_LIST=${URL_LIST} >> $GITHUB_ENV

    - name: Comment to PR
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo } } = context;
          const urlList = '${{ env.URL_LIST }}'.split(',').map(x => `- ${x}`).join('\n');
          github.issues.createComment({ issue_number, owner, repo, body: `Preview URL:\n${urlList}` });

