# release ブランチを本番環境にデプロイ
name: Release Deploy

on:
  # 手動実行時
  workflow_dispatch:
    inputs:
      generator_branch:
        description: 'Branch name of generator repository'
        required: false
        default: 'main'
      s3_bucket_name:
        description: 'S3 bucket name'
        required: false
      s3_region:
        description: 'Region of S3 bucket'
        required: false
        default: 'ap-northeast-1'
      cloudfront_distribution:
        description: 'ID of CloudFront Distribution'
        required: false
      google_adsense_url:
        description: 'URL of Google Adsense'
        required: false
      google_programmable_search_url:
        description: 'URL of Google Programmable Search'
        required: false

  # デプロイ前処理の実行後
  workflow_run:
    workflows:
      - Release Pre-process
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Release

    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTENT_PATH: ${{ github.workspace }}/content
      GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      NO_CACHE: ${{ secrets.NO_CACHE }}
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      S3_BUCKET_NAME: ${{ github.event.inputs.s3_bucket_name || secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ github.event.inputs.s3_region || secrets.S3_REGION }}
      GOOGLE_ADSENSE_URL: ${{ github.event.inputs.google_adsense_url || secrets.GOOGLE_ADSENSE_URL }}
      GOOGLE_PROGRAMMABLE_SEARCH_URL: ${{ github.event.inputs.google_programmable_search_url || secrets.GOOGLE_PROGRAMMABLE_SEARCH_URL }}
      S3_REMOVE_NONEXISTENT_OBJECTS: true

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.generator_branch || secrets.GENERATOR_BRANCH }}
        repository: mseninc/blog-gatsby

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: content
        
    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v4
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-blog-release-gatsby-${{ hashFiles('package-lock.json') }}
    
    - run: ls -la

    - name: Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      run: npm install --omit=dev

    - name: Build
      run: node_modules/.bin/gatsby build --verbose

    - name: Deploy
      run: node_modules/.bin/gatsby-plugin-s3 deploy

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        AWS_REGION: us-east-1
        DISTRIBUTION: ${{ github.event.inputs.cloudfront_distribution || secrets.CLOUDFRONT_DISTRIBUTION }}
        PATHS: '/*'
