name: Release Facebook

on:
  workflow_dispatch:
  push:
    branches:
      - release
      - 317-add-workflow-for-facebook-post

jobs:
  release_facebook:
    runs-on: ubuntu-latest

    environment:
      name: Release

    env:
      BLOG_URL: https://mseeeen.msen.jp/rss.xml
      RSS_FILENAME: rss.xml 
      RSS_CONVERTER: https://api.rss2json.com/v1/api.json?rss_url=

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get data from RSS feed
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            const rssUrl = '${{ env.RSS_CONVERTER }}${{ env.BLOG_URL }}';
            
            const response = await fetch(rssUrl);
            const data = await response.json();
            fs.writeFileSync('${{ env.RSS_FILENAME }}', JSON.stringify(data.items));
        
      - name: Caching Hash
        id: blog-posts-cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: blog-post-${{ hashFiles(env.RSS_FILENAME) }}          
      
      - if: ${{ steps.blog-posts-cache.outputs.cache-hit != 'true' }}
        name: Get latest posts
        id: latest-data
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = fs.readFileSync('${{ env.RSS_FILENAME }}');
            const items = JSON.parse(data)

            let date
            let photoUrl
            for (const item of items) {
              if (!date || new Date(date).getTime() < new Date(item.pubDate).getTime()) {
                break;
              }
              date = item.pubDate;
              photoUrl = item.enclosure.link;
            }

            return photoUrl

      - name: Post data to Facebook
        uses: actions/github-script@v7
        with:
          script: |
            const { exec } = require('child_process');
            exec('
            curl -i -X POST \
              -d "url=${{ steps.latest-data.outputs.result }}" \
              -d "published=true" \
              -d "access_token=${{ secrets.FACEBOOK_APP_ID }}|${{ secrets.FACEBOOK_APP_SECRET }}" \
              "https://graph.facebook.com/me/photos"                
            , (error, stdout, stderr) => {
              if (error) {
                console.error(`Error: ${error}`);
                return;
              }
              if (stderr) {
                console.error(`stderr: ${stderr}`);
                return;
              }
              console.log(`stdout: ${stdout}`);
            });

  