# release ブランチを本番環境にデプロイ
name: Release Deploy

on:
  # 手動実行時
  workflow_dispatch:

  # デプロイ前処理の実行後
  workflow_run:
    workflows:
      - Release Pre-process
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: Release

    env:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTENT_PATH: ${{ github.workspace }}/content
      GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      NO_CACHE: ${{ secrets.NO_CACHE }}
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_REGION: ${{ secrets.S3_REGION }}
      S3_REMOVE_NONEXISTENT_OBJECTS: true

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ secrets.GENERATOR_BRANCH }}
        repository: mseninc/blog-gatsby

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: content
        
    - name: Caching Gatsby
      id: gatsby-cache-build
      uses: actions/cache@v3
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-blog-release-gatsby
    
    - run: ls -la

    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: node_modules/.bin/gatsby build --verbose

    - name: Deploy
      run: node_modules/.bin/gatsby-plugin-s3 deploy

    - name: Invalidate CloudFront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        AWS_REGION: ${{ env.AWS_DEFAULT_REGION }}
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        PATHS: '/*'
