# release ブランチのデプロイの前に呼び出されるワークフロー
# - リリース日設定
# - 画像最適化
name: Release Pre-process

on:
  # 手動実行時
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Input SHA of the target commit'
        required: true
        default: ''
      fetch_depth:
        description: 'Input commit depth to fetch'
        required: true
        default: '2'
      issue_number:
        description: 'Input PR #'
        required: false
        default: '2'

  # release ブランチへのプルリクエストが閉じられたときに実行
  # ※ PR にコメントするため PR 起点とする
  # ※ 別のワークフローからマージする場合は Actions の GITHUB_TOKEN では後続のワークフローが実行されないため、別途発行した Personal Access Token で実行すること
  # ※ 「マージ時」に限定する場合は job や steps で if: github.event.pull_request.merged == true をチェックすること
  pull_request:
    branches:
      - release
    types: [closed]

jobs:

  process:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.inputs.commit_sha

    environment:
      name: Release
      
    env:
      GIT_BRANCH: release
      COMMIT_SHA: ${{ github.event.inputs.commit_sha || github.sha }}
      FETCH_DEPTH: ${{ github.event.inputs.fetch_depth || '2' }}

    steps:

      # Git 初期化 & 必要なファイルのチェックアウト
      # 直前のコミットとの差分ファイルと処理に必要なファイルのみを sparse-checkout
      - name: Checkout content
        run: |
          echo "COMMIT_SHA: ${COMMIT_SHA}"
          git init -q
          git remote add origin https://${{secrets.CI_GITHUB_USER}}:${{secrets.CI_GITHUB_TOKEN}}@github.com/${{github.repository}}.git
          git fetch --depth ${FETCH_DEPTH}
          git config core.sparsecheckout true
          echo .gitignore >> .git/info/sparse-checkout
          echo .github >> .git/info/sparse-checkout
          echo package.json >> .git/info/sparse-checkout
          echo package-lock.json >> .git/info/sparse-checkout
          git -c core.quotepath=false diff ${COMMIT_SHA}^ ${COMMIT_SHA} --name-only >> .git/info/sparse-checkout
          cat .git/info/sparse-checkout
          git checkout -q ${GIT_BRANCH}

      # リリース日の設定
      - name: Set release date
        id: set-release-date
        run: chmod +x .github/scripts/set-release-date.sh && .github/scripts/set-release-date.sh

      # Node & npm 初期化
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # npm install
      - name: npm install
        run: npm install --omit=dev

      # 画像最適化
      - name: Execute image-optimization
        id: optimization
        run: |
          SECONDS=0
          RESULT=$(node .github/scripts/optimize-images.js . --no-backup)
          echo ${RESULT}
          RESULT="${RESULT//$'\n'/\\n}"
          echo "result=$RESULT" >> $GITHUB_OUTPUT
          echo "elapsed=$SECONDS" >> $GITHUB_OUTPUT

      # コミットプッシュ
      - name: Commit & push
        id: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -u
          git commit -m "Release pre-process"
          git push origin ${GIT_BRANCH}
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT

      # Pull request に画像最適化の結果をコメント
      - name: Comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number }, repo: { owner, repo } } = context
            const commitHash = '${{ steps.commit.outputs.hash }}'
            const elapsed = '${{ steps.optimization.outputs.elapsed }}s'
            const result = '${{ steps.optimization.outputs.result }}'.trim()
            const issue_number = number || '${{ github.event.inputs.issue_number }}'
            if (result) {
              const resultText = result
                .split('\\n')
                .join('\n')
                .replace(/^/gm, '- ')
                .replace(/"([^"]+)"/g, (_, p1) => {
                  const baseUrl = `https://github.com/${owner}/${repo}/blob/${commitHash}/`
                  const relPath = encodeURI(p1.replace(/^(\.\/|)/, ''))
                  const fileName = p1.match(/[^/]+$/, '$@')
                  return `[${fileName}](${baseUrl}${relPath})`
                })
              const body = `### Image optimization\ncommit: ${commitHash} elapsed: ${elapsed}\n${resultText}`
              github.rest.issues.createComment({ issue_number, owner, repo, body })
            }
