name: Release Facebook

on:
  workflow_dispatch:
  push:
    branches:
      - release
      - 317-add-workflow-for-facebook-post

jobs:
  release_facebook:
    runs-on: ubuntu-latest

    env:
      BLOG_URL: https://mseeeen.msen.jp/rss.xml
      RSS_FILENAME: rss.xml 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get data from RSS feed
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            const rssUrl = '${{ env.BLOG_URL }}';
            const outputFile = '${{ env.RSS_FILENAME }}';
            
            fetch(rssUrl)
            .then(response => response.text())
            .then(str => new window.DOMParser().parseFromString(str, "text/xml"))
            .then(data => {
              const items = data.querySelectorAll("item");
              fs.writeFileSync(outputFile, JSON.stringify(items));
            })
            ;
        
      - name: Caching Hash
        id: blog-posts-cache
        uses: actions/cache@v4
        with:
          path: .cache
          key: blog-post-${{ hashFiles(env.RSS_FILE_PATH) }}          
      
      - if: ${{ steps.blog-posts-cache.outputs.cache-hit != 'true' }}
        name: Get latest posts
        id: latest-data
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const str = fs.readfilesync(outputFile, data);

            let date
            let photoUrl
            for (const item of JSON.parse(str)) {
              if (!date || new Date(date).getTime() < new Date(item.pubDate).getTime()) {
                break;
              }
              date = item.pubDate;
              photoUrl = item['media:content'][url];
            }

            return photoUrl

      - name: Post data to Facebook
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = fs.readfilesync(outputFile, data);

            const { exec } = require('child_process');
            exec('
            curl -i -X POST \
              -d "url=${{ steps.latest-data.outputs.result }}" \
              -d "published=false" \
              -d "access_token=${{ secrets.FACEBOOK_APP_ID }}|${{ secrets.FACEBOOK_APP_SECRET }}" \
              "https://graph.facebook.com/me/photos"                
            , (error, stdout, stderr) => {
              if (error) {
                console.error(`Error: ${error}`);
                return;
              }
              if (stderr) {
                console.error(`stderr: ${stderr}`);
                return;
              }
              console.log(`stdout: ${stdout}`);
            });

  