name: Textlint with reviewdog

on:
  pull_request:
    branches:
      - release

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout content
        run: |
          BRANCH_NAME=${GITHUB_HEAD_REF#refs/heads/}
          echo ${BRANCH_NAME}
          git init -q
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --depth 1
          git config core.sparsecheckout true
          echo .github >> .git/info/sparse-checkout
          echo .textlintrc >> .git/info/sparse-checkout
          echo package.json >> .git/info/sparse-checkout
          echo package-lock.json >> .git/info/sparse-checkout
          git -c core.quotepath=false diff origin/release origin/${BRANCH_NAME} --name-only | grep -rEI '\.md$' - >> .git/info/sparse-checkout
          cat .git/info/sparse-checkout
          git checkout -q origin/${BRANCH_NAME}

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - name: npm install
        run: npm ci

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1

      - run: reviewdog -version

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx textlint -f checkstyle . \
            | reviewdog -f=checkstyle -name="textlint" -diff="git diff ${{ github.event.pull_request.base.ref }}" -reporter=github-pr-review
