name: Report term summary

on:
  workflow_dispatch:
  schedule:
    # JST 月 9:00 (UTC のため -9h)
    - cron: '0 0 * * 1'
  push:
    branches:
      - term-summary

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Release

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Make summary
      id: make-summary
      run: |
        chmod +x .github/scripts/term-summary.sh
        OUTPUT=$(.github/scripts/term-summary.sh)
        TERM=$(echo ${OUTPUT} | head -n 1')
        SUMMARY=$(echo ${OUTPUT} | tail -n +3 | awk '{printf $1":"$2";"}')
        echo "::set-output name=term::$TERM"
        echo "::set-output name=summary::$SUMMARY"

    - name: Report to slack
      uses: 8398a7/action-slack@v3
      env:
        TERM: ${{ steps.make-summary.outputs.term }}
        SUMMARY: ${{ steps.make-summary.outputs.summary }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: custom
        custom_payload: |
          {
            text: 'ブログの執筆状況を報告するよ :rola-ok:',
            attachments: [
              {
                color: 'good',
                text: process.env.TERM,
                fields: process.env.SUMMARY.split(';')
                  .map(x => x.split(':'))
                  .map(x => ({
                      'title': x[0],
                      'value': x[1],
                      'short': true,
                  })),
              },
            ]
          }
